name: sales-system
version: 0.1.0.0
github: "githubuser/sales-system"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/sales-system#readme>

default-extensions:
  - BlockArguments
  - LambdaCase
  - DuplicateRecordFields
  - MultiParamTypeClasses
  - ExistentialQuantification

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6 && < 0.7
  - stm >= 2.5 && < 3.0
  - async >= 2.1 && < 3

library:
  source-dirs: src

executables:
  sales-system-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sales-system

tests:
  sales-system-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sales-system
